### ISSUE TITLE
where is CSTParser.BinarySyntaxOpCall?

### ISSUE THREAD

**Issue by aminya** [julia-vscode/CSTParser.jl#102]
I am trying to upgrade [Deprecations](https://github.com/aminya/Deprecations.jl).jl  for [FemtoCleaner](https://github.com/aminya/FemtoCleaner.jl/tree/Amin_Julia1). In Deprecations code  CSTParser.BinarySyntaxOpCall is used a lot [like here.](https://github.com/JuliaComputing/Deprecations.jl/blob/9e48ff7e1c477360425ef08f70d5a385749b737c/src/CSTUtils/treewalking.jl#L4) 

I found [its definition here](https://github.com/julia-vscode/CSTParser.jl/blob/ceb3adc2186ed60e5d4cecfc9f81386c45efdc86/src/spec.jl#L217).

What has happened to this in recent versions?

**Comment by ZacLN** [comment]
Sorry for the delayed reply. Dedicated expression datatypes (e.g. BinarySyntaxOpCall, UnaryOpCall, etc.) were replaced by a single expression type (`EXPR`). The 'type' of expressions are now stored in the `.typ` field which should be accessed using `CSTParser.typof(x::EXPR)`. 

The change was made for increasing parsing speed.
