### ISSUE TITLE
short-form anon func not parsed as function definition

### ISSUE THREAD

**Issue by pfitzseb** [julia-vscode/CSTParser.jl#103]
and also doesn't open a new `scope`:
```
julia> CSTParser.parse("function (a,b); a+b; end").scope
Root scope:
[]
[]


julia> CSTParser.parse("(a,b) -> a+b ").scope
```

Is that intended? I had expected short form anonymous functions to be parsed as `FunctionDef`s as well.

**Comment by ZacLN** [comment]
Right you are on the missing scope. `FunctionDef` is only used to refer to the 4 arg (kw, signature, body, `end`) syntax.

Fixed: https://github.com/julia-vscode/CSTParser.jl/commit/cac414eda9c7a49c0dd91e04296fb15daae3d386
