### ISSUE TITLE
Parsing input error for `test/show.jl` in julia repo

### ISSUE THREAD

**Issue by domluna** [julia-vscode/CSTParser.jl#107]
While trying out formatting on the entire julia repo, I encountered a file, [test/show.jl](https://github.com/JuliaLang/julia/blob/master/test/show.jl) which CSTParser cannot parse.

The formatter checks if the input can be parsed before proceeding. 

https://github.com/domluna/JuliaFormatter.jl/blob/577138b80e5f40a61e695e55c723a10492779b6d/src/JuliaFormatter.jl#L214-L215

```julia
julia> s = read("test/show.jl") |> String;
julia> x, ps = CSTParser.parse(CSTParser.ParseState(s), true);
julia> ps.errored
true
```

This is the only file in the entire julia repo where this occurs.

**Comment by ZacLN** [comment]
Hi, I can't replicate this on my system probably meaning  this is fixed on the `meta` branch to be merged soon. Will check back after merging

**Comment by domluna** [comment]
I should mention this was with a checkout of 1.3.0-rc4 but it looks like with the most recent version of the file and v1.0.0 it still errors.

**Comment by domluna** [comment]
still errors with v1.1.0

**Comment by ZacLN** [comment]
This is due to https://github.com/JuliaLang/julia/pull/32408, I'm having a look

**Comment by ZacLN** [comment]
https://github.com/julia-vscode/CSTParser.jl/pull/118 is a WIP fix for this but it will require careful handling within StaticLint/LanguageServer. I'm tempted to leave this until the next LS release so I can think about this

**Comment by davidanthoff** [comment]
Sounds good, I moved it to the next milestone!

**Comment by ZacLN** [comment]
This is fixed on CSTParser#master, the next release should be pretty soon
