### ISSUE TITLE
LanguagServer fails to import with CSTParser@1.1.0

### ISSUE THREAD

**Issue by non-Jedi** [julia-vscode/CSTParser.jl#114]
Per https://github.com/julia-vscode/LanguageServer.jl/pull/416#issuecomment-560406919

**Comment by davidanthoff** [comment]
Yeah, CSTParser 1.1.0 was breaking, so should have been tagged as 2.0.0, sorry. I believe Zac is working on a PR for LS that makes that work with CSTParser 1.1.0, and then things should work again.

**Comment by non-Jedi** [comment]
Could you fix the compat for LanguageServer 1.0.0 in the General registry when you get a chance? I was going to do so myself but I'm finding the Compat.toml format byzantine, and I can't seem to find any documentation on it.

**Comment by davidanthoff** [comment]
I don't think one can declare something as incompatible when it has a semver version number that declares it as compatible...

I think our options at this point are: 1) yank the CSTParser release (and rerelease as 2.0.0), 2) release CSTParser 1.1.1 that is essentially identical to the previous version of CSTParser (this is similar to yanking), or 3) let @ZacLN finish his work to make LS compat with the latest CSTParser and then quickly tag a new LS.

My sense is that he is pretty far with 3), but I don't really know... I'm not sure how the whole "yank" a release stuff works, and how robust that is, so my preference would be to go with 3) at this point. Assuming that can be wrapped up in a few days.

**Comment by non-Jedi** [comment]
Looking at the format in https://github.com/JuliaRegistries/General/blob/master/L/LanguageServer/Compat.toml, it seems like the second number in the "1.0.1-1"-type strings implies an upper bound of some sort, so I think adding an upper bound should be possible. Actually, I know it's possible since you can [restrict compatibility in Project.toml to only a single version](https://julialang.github.io/Pkg.jl/v1/compatibility/). I'm going to create a discourse thread asking if there's documentation on the semantics of Compat.toml.

**Comment by davidanthoff** [comment]
I think `1.0.1-1`means anything newer than `1.0.1` and older than `2.0.0`. But you are right, given that one can specify `=1.1.1` in the `Project.toml`, there must be some way to express that in the registry...

**Comment by KristofferC** [comment]
`1.0-1.0` might do it.

**Comment by davidanthoff** [comment]
Ok, I thought about it a bit more, and here is what I'm going to do:

I will release a patch release of CSTParser 1.1.1 next that is identical to CSTParser 1.0.0. That way we will have solved all the broken packages problems downstream.

I'll then tag a new CSTParser 2.0.0 on `master` that will have the new stuff in it.

Ideally everyone holds off with further tags/fixes until I'm through with this.

**Comment by davidanthoff** [comment]
CSTParser 1.1.1 is tagged in the registry, and I think that by itself should be enough to get everything back into working condition.

CSTParser 2.0.0 registration is pending, should be through in a moment.
