### ISSUE TITLE
code starting with newline is not parsed 

### ISSUE THREAD

**Issue by orialb** [julia-vscode/CSTParser.jl#179]
Hi,
Not sure if this is a bug or it shouldn't be supported, but it seems that code which starts with a newline is not being parsed properly (I encountered this while trying to parse some file which had an empty first line):
```julia
julia> CSTParser.parse("\nprintln(\"parse me\")")
  1:1   NOTHING:

julia> CSTParser.parse("println(\"parse me\")")
  1:19  Call
  1:7    println
  8:8    (
  9:18   STRING: parse me
 19:19   )
```

**Comment by non-Jedi** [comment]
This is what the `cont` optional arg to `parse` is for. See the `parse` docstring:

```julia
julia> CSTParser.parse("\nprintln(\"parse me\")", true)
  1:20  FileH
  1:1    NOTHING: 
  2:20   Call
  2:8     println
  9:9     (
 10:19    STRING: parse me
 20:20    )
```

I believe the behavior without `cont=true` is that it only parses the first complete expression it encounters. I'll leave this open in case @ZacLN believes that it should continue parsing past a newline until it encounters an expression rather than treating a '\n' as an expression by itself.

**Comment by orialb** [comment]
Thanks! I've read about the `cont` argument at some point but forgot about it, sorry.

Just out of curiosity, why is the default behavior `cont=false` ? Wouldn't one expect a function called `parse` to just parse the whole string by default? Or is it actually more typical of functions that do parsing to have the behavior of stopping at the first expression they can parse? (I don't have much experience with code parsing, so just asking)

**Comment by non-Jedi** [comment]
I think for the purpose of a CST which is round-trippable from/to text, top-level whitespace must be represented as an independent expression--otherwise you lose the information on the whitespace existing. But I'll defer to @ZacLN on whether this is a bug or the desired behavior.

**Comment by ZacLN** [comment]
Hi, this is intended behaviour fur the reason given above

**Comment by orialb** [comment]
Sorry for the noise and thanks for the quick response!
