### ISSUE TITLE
Parsing error on :var"name"

### ISSUE THREAD

**Issue by visr** [julia-vscode/CSTParser.jl#198]
Got to this from JuliaFormatter, trying to format this line: https://github.com/KristofferC/TOMLX.jl/blob/4646119c785f529d59c303ad113dc43be46b9c36/src/parser.jl#L152

I see `var"name"` support was added in #118, but this seems to be an edge case:

```julia
julia> using CSTParser

julia> :var"name"
:name

julia> :(var"name")
:name

julia> :(r"name")
:(r"name")

julia> :r"name"  # for normal string macros this is invalid
ERROR: syntax: extra token """ after end of expression
Stacktrace:
 [1] top-level scope at none:1

julia> CSTParser.parse(":(var\"name\")")
  1:12  Quote
  1:1    OP: COLON
  2:12   InvisBrackets
  2:2     (
  3:11    name
 12:12    )


julia> CSTParser.parse(":var\"name\"")
  1:10  ErrorToken
  1:4    Quotenode
  1:1     OP: COLON
  2:4     var
  5:10   STRING: name
```

**Comment by non-Jedi** [comment]
We should check with upstream whether `:var"name"` is intended to be valid Julia code or whether this is a bug.

**Comment by ZacLN** [comment]
The parser accepts symbols following `:` and `var"sfd"` is a symbol so I'm fairly certain this is intended. Not to prevent checking upstream, we want to mimic unintended behaviour on the part of the scheme parser until it is fixed

**Comment by c42f** [comment]
Upstream behavior of `var` in the scheme parser with respect to quoting with `:` is consistent with other atoms:

```
julia> :(1)
1

julia> :1
1

julia> :"hi"
"hi"

julia> :("hi")
"hi"

julia> :(name)
:name

julia> :name
:name
```

so I'd say this was a bug in CSTParser which has now been fixed. (Great turn around time @zacln!)
