### ISSUE TITLE
Empty keyword arguments should still be parsed as Parameters?

### ISSUE THREAD

**Issue by domluna** [julia-vscode/CSTParser.jl#207]
https://github.com/domluna/JuliaFormatter.jl/issues/285

It seems to me "(;)" should still be parsed as (ignore the numbers)

```
  1:7   TupleH
  1:2    (
  3:6    Parameters
  7:7    )

```

instead of 

```
julia> CSTParser.parse("(;)")
  1:3   TupleH
  1:2    (
  3:3    )

```

as is done for `Call` "f(;)"

```
julia> CSTParser.parse("f(;)")
  1:4   Call
  1:1    f
  2:3    (
  4:3    Parameters
  4:4    )

```

**Comment by nickrobinson251** [comment]
seems a couple people have hit this recently (via JuliaFormatter): https://github.com/domluna/JuliaFormatter.jl/issues/343#issue-759717880 and https://github.com/domluna/JuliaFormatter.jl/issues/285#issuecomment-745577668

**Comment by ZacLN** [comment]
This is addressed in https://github.com/julia-vscode/CSTParser.jl/pull/190 so I think we'll just wait for that to be ready for merging
