### ISSUE TITLE
ambiguous unary parse

### ISSUE THREAD

**Issue by domluna** [julia-vscode/CSTParser.jl#223]
```
julia> collect(CSTParser.parse("A..."))
2-element Vector{Any}:
   1:1   A
   1:3   OP: ...

julia> collect(CSTParser.parse("<:A"))
2-element Vector{Any}:
   1:1   A
   1:2   OP: <:
```

The order is the same yet the latter op occurs before the identifier. Is there a way to if the op occurred before or after the argument?

**Comment by ZacLN** [comment]
This is just a plain old error with the iterator. Fix: https://github.com/julia-vscode/CSTParser.jl/pull/225
