### ISSUE TITLE
Lots of parse errors for Julia base

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/CSTParser.jl#289]
When I open the repo for Julia itself in VS Code, I get 36 parsing errors for the v1.6.1 tag and more than 50 parsing errors for the current `master` branch. Presumably when the linter complains about a parsing error, the source of that problem is here in CSTParser? In any case, we should try to fix this.

I also thought that we actually had parsing of the Julia base repo as one of our test cases?

**Comment by pfitzseb** [comment]
CSTParser or Tokenize, yes. And I thought so too...
