### ISSUE TITLE
Not a priority right now but we shouldn't need to special case conversion so should look to fix the underlying inconsistency w/ the scheme parser

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/CSTParser.jl#297]
Not a priority right now but we shouldn't need to special case conversion so should look to fix the underlying inconsistency w/ the scheme parser

_Originally posted by @ZacLN in https://github.com/julia-vscode/CSTParser.jl/pull/296#discussion_r676855942_

**Comment by pfitzseb** [comment]
Yeah, that's basically what I reverted [here](https://github.com/julia-vscode/CSTParser.jl/pull/296/files#diff-536ae4e751c4f70b89593c01d8b0b12402a91c45b21409cc4aa54caaa9cc1967L235-L242). Originally I had the right order in the `EXPR`, but that failed during `iterate`, so this was easier for me than wrapping my head around how iteration works :P

_Originally posted by @pfitzseb in https://github.com/julia-vscode/CSTParser.jl/pull/296#discussion_r676874721_
