### ISSUE TITLE
Track the number of semicolons in multidimensional expressions

### ISSUE THREAD

**Issue by domluna** [julia-vscode/CSTParser.jl#323]
ref https://github.com/domluna/JuliaFormatter.jl/issues/532

The current way this is being done in JuliaFormatter is kind of hacky and could be greatly simplified if this is stored in the `meta` or `trivia` fields. Is this a viable approach?

**Comment by pfitzseb** [comment]
Semicolons aren't explicitly tracked on master, but `ncat`/`nrow` expressions now include their dimensionality. That should almost always be enough info, except for
```
[1 2;;
 3 4]
```
I think. It's of course always valid to rewrite that to `[1 2 3 4]`, so I'm not sure if you strictly need that info.
