### ISSUE TITLE
peekchar error in Atom

### ISSUE THREAD

**Issue by tlienart** [julia-vscode/CSTParser.jl#327]
Hello,

Maybe this should be moved to Juno.jl, I started getting this kind of error (with a string of "beeps") when editing files in a package with Atom.

* Julia 1.7.2
* Atom 1.58
* Julia client 0.12.6
* language-julia 0.22.1

<img width="464" alt="Screenshot 2022-02-08 at 12 31 52" src="https://user-images.githubusercontent.com/10897531/152979112-22d3fe4d-2029-4dbb-8ddc-44f3b3c99448.png">

No specific changes to my setup (the latest change I'm thinking might be relevant is the update from 1.7.1 to 1.7.2).

**Comment by pfitzseb** [comment]
Try pinning Tokenize on 0.5.21. The issue here is that Atom requires CSTParser 2.x, which can't deal with the new Tokenize release.

@KristofferC Maybe we should yank Tokenize@0.5.22 and re-tag as 0.6?
