### ISSUE TITLE
Incorrect Parse in global statement

### ISSUE THREAD

**Issue by Xpectuer** [julia-vscode/CSTParser.jl#339]
When global statement is parsed, there is a incorrect behavior.
Here is the example
source:
```julia
global a = 1, b
```
The statement above is parsed into: 
```scheme
(global 
(assign a (tuple 1 b)))
```
whereas the expected one is:
```scheme
(global 
(assign a  1) b)
```

<img width="364" alt="截屏2022-05-07 下午1 44 30" src="https://user-images.githubusercontent.com/43370918/167240333-45b0c5d0-68aa-40f8-b130-776992d3581e.png">

Hope for a fix.

**Comment by pfitzseb** [comment]
What makes you think that this is the expected behaviour? We're matching `Meta.parse` here:
```
julia> CSTParser.parse("global a, b = 2")
  1:15  global
  1:8      1:2   OP: =
  1:5     tuple
  1:1      a
  2:3      b
  6:6     INTEGER: 2

julia> CSTParser.to_codeobject(CSTParser.parse("global a=2, b"))
:(global a = (2, b))

julia> Meta.parse("global a=2, b")
:(global a = (2, b))
```
