### ISSUE TITLE
Command parsed possibly incorrectly

### ISSUE THREAD

**Issue by domluna** [julia-vscode/CSTParser.jl#349]
```
julia> x = """
       x = ```
       my_cmd very_long command that really should be multi-line but isn't, and exceeds the character limit, will be indented forever by repeated calls to format
       ```
       """
"x = ```\nmy_cmd very_long command that really should be multi-line but isn't, and exceeds the character limit, will be indented forever by repeated calls to format\n```\n"

julia> cst = CSTParser.parse(x)
  1:167   1:2   OP: =
  1:2    x
  3:165  macrocall
  3:2     globalrefcmd
  3:2     NOTHING: nothing
  3:165   TRIPLESTRING: my_cmd very_long command that really should be multi-line but isn't, and exceeds the character limit, will be indented forever by repeated calls to format
```

I'm not sure if this is incorrect or not but should this be a macrocall? Wouldn't a TRIPLECMD node make more sense?

Equivalent with triple string

```
julia> s = """
       x = \"""
       my_cmd very_long command that really should be multi-line but isn't, and exceeds the character limit, will be indented forever by repeated calls to format
       \"""
       """
"x = \"\"\"\nmy_cmd very_long command that really should be multi-line but isn't, and exceeds the character limit, will be indented forever by repeated calls to format\n\"\"\"\n"

julia> cst = CSTParser.parse(s)
  1:167   1:2   OP: =
  1:2    x
  3:165  TRIPLESTRING: my_cmd very_long command that really should be multi-line but isn't, and exceeds the character limit, will be indented forever by repeated calls to format
```

https://github.com/domluna/JuliaFormatter.jl/issues/613

**Comment by pfitzseb** [comment]
Mh, this has been how we've been parsing Cmds for the last couple of releases at least. I could change back to CMD/TRIPLECMD heads, but that's likely to be more breaking at this point...

**Comment by domluna** [comment]
for my use case it's fine the way it is I just needed to add an extra condition to a function

I was just wondering if it was intended to be parsed like this

**Comment by pfitzseb** [comment]
Not originally, but I don't feel like changing this after all this time :)
